-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MPCwithMADS_round_fixed_54_15_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (50 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (53 downto 0) );
end;


architecture behav of MPCwithMADS_round_fixed_54_15_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv51_0 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv55_4000000000 : STD_LOGIC_VECTOR (54 downto 0) := "0000000000000000100000000000000000000000000000000000000";
    constant ap_const_lv39_0 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal p_Result_1_fu_64_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_reg_117 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln703_fu_102_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal trunc_ln703_reg_122 : STD_LOGIC_VECTOR (53 downto 0);
    signal x_cast_fu_40_p0 : STD_LOGIC_VECTOR (50 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_Val2_s_fu_44_p1 : STD_LOGIC_VECTOR (50 downto 0);
    signal p_Val2_s_fu_44_p2 : STD_LOGIC_VECTOR (50 downto 0);
    signal sext_ln104_fu_50_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal p_Result_1_fu_64_p1 : STD_LOGIC_VECTOR (50 downto 0);
    signal p_Result_s_fu_54_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal x_cast_fu_40_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal x_pos_fu_72_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln703_fu_80_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal ret_V_fu_84_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_Result_3_fu_90_p5 : STD_LOGIC_VECTOR (54 downto 0);
    signal sub_ln703_fu_106_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                p_Result_1_reg_117 <= p_Result_1_fu_64_p1(50 downto 50);
                trunc_ln703_reg_122 <= trunc_ln703_fu_102_p1;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        sub_ln703_fu_106_p2 when (p_Result_1_reg_117(0) = '1') else 
        trunc_ln703_reg_122;
    p_Result_1_fu_64_p1 <= x;
    p_Result_1_fu_64_p3 <= p_Result_1_fu_64_p1(50 downto 50);
    p_Result_3_fu_90_p5 <= (ret_V_fu_84_p2(54 downto 39) & ap_const_lv39_0);
    
    p_Result_s_fu_54_p4_proc : process(sext_ln104_fu_50_p1)
    begin
        p_Result_s_fu_54_p4 <= sext_ln104_fu_50_p1;
        p_Result_s_fu_54_p4(53) <= ap_const_lv1_0(0);
    end process;

    p_Val2_s_fu_44_p1 <= x;
    p_Val2_s_fu_44_p2 <= std_logic_vector(unsigned(ap_const_lv51_0) - unsigned(p_Val2_s_fu_44_p1));
    ret_V_fu_84_p2 <= std_logic_vector(unsigned(zext_ln703_fu_80_p1) + unsigned(ap_const_lv55_4000000000));
        sext_ln104_fu_50_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_44_p2),54));

    sub_ln703_fu_106_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(trunc_ln703_reg_122));
    trunc_ln703_fu_102_p1 <= p_Result_3_fu_90_p5(54 - 1 downto 0);
    x_cast_fu_40_p0 <= x;
        x_cast_fu_40_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_cast_fu_40_p0),54));

    x_pos_fu_72_p3 <= 
        p_Result_s_fu_54_p4 when (p_Result_1_fu_64_p3(0) = '1') else 
        x_cast_fu_40_p1;
    zext_ln703_fu_80_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_pos_fu_72_p3),55));
end behav;
