// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MPCwithMADS_generatePollMatrix (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        pollMatrix_address0,
        pollMatrix_ce0,
        pollMatrix_we0,
        pollMatrix_d0,
        optimum_V_0,
        optimum_V_1
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] p_read;
input  [5:0] p_read1;
input  [5:0] p_read2;
input  [5:0] p_read3;
output  [2:0] pollMatrix_address0;
output   pollMatrix_ce0;
output   pollMatrix_we0;
output  [17:0] pollMatrix_d0;
input  [17:0] optimum_V_0;
input  [17:0] optimum_V_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pollMatrix_ce0;
reg pollMatrix_we0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [19:0] R1_V;
reg  signed [19:0] R2_V;
wire   [1:0] add_ln19_fu_277_p2;
reg   [1:0] add_ln19_reg_606;
wire    ap_CS_fsm_state2;
wire   [0:0] trunc_ln20_fu_289_p1;
reg   [0:0] trunc_ln20_reg_614;
wire   [0:0] icmp_ln19_fu_283_p2;
wire   [17:0] currentPoint_int_V_1_fu_293_p3;
reg   [17:0] currentPoint_int_V_1_reg_620;
wire   [17:0] currentPoint_int_V_1_1_fu_300_p3;
reg   [17:0] currentPoint_int_V_1_1_reg_625;
wire  signed [5:0] rhs_fu_307_p3;
reg  signed [5:0] rhs_reg_630;
wire   [6:0] ret_fu_317_p2;
reg   [6:0] ret_reg_636;
wire   [35:0] mesh_V_1_1_fu_368_p3;
wire    ap_CS_fsm_state3;
wire   [35:0] mesh_V_1_2_fu_375_p3;
wire  signed [17:0] sext_ln708_fu_402_p1;
reg  signed [17:0] sext_ln708_reg_657;
wire    ap_CS_fsm_state6;
wire  signed [17:0] sext_ln708_1_fu_426_p1;
reg  signed [17:0] sext_ln708_1_reg_662;
wire   [1:0] add_ln42_fu_430_p2;
wire    ap_CS_fsm_state7;
wire   [17:0] randomVector_V_1_fu_446_p3;
wire   [0:0] icmp_ln42_fu_436_p2;
wire   [17:0] randomVector_V_1_1_fu_453_p3;
wire   [1:0] add_ln44_fu_460_p2;
reg   [1:0] add_ln44_reg_685;
wire    ap_CS_fsm_state9;
wire   [2:0] tmp_3_cast_fu_470_p3;
reg   [2:0] tmp_3_cast_reg_690;
wire  signed [25:0] r_V_3_fu_492_p3;
reg  signed [25:0] r_V_3_reg_698;
wire   [0:0] icmp_ln44_fu_478_p2;
wire   [25:0] lhs_fu_508_p3;
reg   [25:0] lhs_reg_703;
wire   [2:0] add_ln45_fu_516_p2;
reg   [2:0] add_ln45_reg_708;
wire    ap_CS_fsm_state10;
reg   [2:0] pollMatrix_addr_reg_713;
wire   [11:0] directions_q0;
reg  signed [11:0] tmp_3_reg_726;
wire    ap_CS_fsm_state11;
wire   [25:0] r_V_4_fu_542_p2;
reg   [25:0] r_V_4_reg_731;
wire    ap_CS_fsm_state12;
reg   [2:0] directions_address0;
reg    directions_ce0;
reg    directions_we0;
reg    directions_ce1;
reg    directions_we1;
wire    grp_generatePollDirections_fu_256_ap_start;
wire    grp_generatePollDirections_fu_256_ap_done;
wire    grp_generatePollDirections_fu_256_ap_idle;
wire    grp_generatePollDirections_fu_256_ap_ready;
wire   [2:0] grp_generatePollDirections_fu_256_directions_address0;
wire    grp_generatePollDirections_fu_256_directions_ce0;
wire    grp_generatePollDirections_fu_256_directions_we0;
wire   [11:0] grp_generatePollDirections_fu_256_directions_d0;
wire   [2:0] grp_generatePollDirections_fu_256_directions_address1;
wire    grp_generatePollDirections_fu_256_directions_ce1;
wire    grp_generatePollDirections_fu_256_directions_we1;
wire   [11:0] grp_generatePollDirections_fu_256_directions_d1;
reg   [35:0] mesh_V_1_09_reg_140;
reg   [35:0] mesh_V_0_08_reg_152;
reg   [17:0] currentPoint_int_V_1_07_reg_164;
reg   [17:0] currentPoint_int_V_0_06_reg_176;
reg   [1:0] i_reg_188;
reg   [17:0] randomVector_V_0_05_reg_199;
reg   [17:0] randomVector_V_1_04_reg_211;
reg   [1:0] i_1_reg_223;
reg   [1:0] i_2_reg_234;
wire   [0:0] icmp_ln45_fu_533_p2;
wire    ap_CS_fsm_state8;
reg   [2:0] j_reg_245;
wire    ap_CS_fsm_state13;
reg    grp_generatePollDirections_fu_256_ap_start_reg;
wire   [63:0] zext_ln46_fu_527_p1;
wire  signed [19:0] grp_fu_562_p2;
wire  signed [19:0] grp_fu_570_p2;
wire  signed [6:0] sext_ln215_fu_313_p1;
wire   [35:0] sh_prom_i_i_i54_fu_338_p1;
wire  signed [31:0] sh_prom_i_i_i_cast_cast_cast_fu_347_p1;
wire   [35:0] sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1;
wire   [0:0] tmp_2_fu_331_p3;
wire   [35:0] r_V_fu_341_p2;
wire   [35:0] r_V_1_fu_354_p2;
wire   [35:0] r_V_5_fu_360_p3;
wire   [15:0] trunc_ln708_1_fu_387_p4;
wire   [15:0] v_V_0_fu_396_p2;
wire   [15:0] trunc_ln708_2_fu_411_p4;
wire   [15:0] v_V_1_fu_420_p2;
wire   [0:0] trunc_ln43_fu_442_p1;
wire   [0:0] trunc_ln46_fu_466_p1;
wire   [25:0] empty_53_fu_484_p1;
wire   [25:0] empty_54_fu_488_p1;
wire   [17:0] empty_55_fu_500_p3;
wire   [2:0] add_ln46_fu_522_p2;
wire   [25:0] ret_V_fu_547_p2;
wire   [5:0] grp_fu_562_p1;
wire   [5:0] grp_fu_570_p1;
reg   [12:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 R1_V = 20'd37027;
#0 R2_V = 20'd317217;
#0 grp_generatePollDirections_fu_256_ap_start_reg = 1'b0;
end

MPCwithMADS_generatePollMatrix_directions #(
    .DataWidth( 12 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
directions_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(directions_address0),
    .ce0(directions_ce0),
    .we0(directions_we0),
    .d0(grp_generatePollDirections_fu_256_directions_d0),
    .q0(directions_q0),
    .address1(grp_generatePollDirections_fu_256_directions_address1),
    .ce1(directions_ce1),
    .we1(directions_we1),
    .d1(grp_generatePollDirections_fu_256_directions_d1)
);

MPCwithMADS_generatePollDirections grp_generatePollDirections_fu_256(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generatePollDirections_fu_256_ap_start),
    .ap_done(grp_generatePollDirections_fu_256_ap_done),
    .ap_idle(grp_generatePollDirections_fu_256_ap_idle),
    .ap_ready(grp_generatePollDirections_fu_256_ap_ready),
    .p_read(randomVector_V_0_05_reg_199),
    .p_read1(randomVector_V_1_04_reg_211),
    .p_read2(p_read),
    .p_read3(p_read1),
    .p_read4(p_read2),
    .p_read5(p_read3),
    .directions_address0(grp_generatePollDirections_fu_256_directions_address0),
    .directions_ce0(grp_generatePollDirections_fu_256_directions_ce0),
    .directions_we0(grp_generatePollDirections_fu_256_directions_we0),
    .directions_d0(grp_generatePollDirections_fu_256_directions_d0),
    .directions_address1(grp_generatePollDirections_fu_256_directions_address1),
    .directions_ce1(grp_generatePollDirections_fu_256_directions_ce1),
    .directions_we1(grp_generatePollDirections_fu_256_directions_we1),
    .directions_d1(grp_generatePollDirections_fu_256_directions_d1)
);

MPCwithMADS_mul_26s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_26s_12s_26_1_1_U92(
    .din0(r_V_3_reg_698),
    .din1(tmp_3_reg_726),
    .dout(r_V_4_fu_542_p2)
);

MPCwithMADS_mul_mul_20s_6ns_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
mul_mul_20s_6ns_20_4_1_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R1_V),
    .din1(grp_fu_562_p1),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

MPCwithMADS_mul_mul_20s_6ns_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
mul_mul_20s_6ns_20_4_1_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R2_V),
    .din1(grp_fu_570_p1),
    .ce(1'b1),
    .dout(grp_fu_570_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generatePollDirections_fu_256_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln42_fu_436_p2 == 1'd1))) begin
            grp_generatePollDirections_fu_256_ap_start_reg <= 1'b1;
        end else if ((grp_generatePollDirections_fu_256_ap_ready == 1'b1)) begin
            grp_generatePollDirections_fu_256_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln42_fu_436_p2 == 1'd0))) begin
        i_1_reg_223 <= add_ln42_fu_430_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_1_reg_223 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_generatePollDirections_fu_256_ap_done == 1'b1))) begin
        i_2_reg_234 <= 2'd0;
    end else if (((icmp_ln45_fu_533_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_2_reg_234 <= add_ln44_reg_685;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_188 <= add_ln19_reg_606;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_188 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        j_reg_245 <= add_ln45_reg_708;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln44_fu_478_p2 == 1'd0))) begin
        j_reg_245 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        R1_V <= grp_fu_562_p2;
        R2_V <= grp_fu_570_p2;
        sext_ln708_1_reg_662 <= sext_ln708_1_fu_426_p1;
        sext_ln708_reg_657 <= sext_ln708_fu_402_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln19_reg_606 <= add_ln19_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln44_reg_685 <= add_ln44_fu_460_p2;
        tmp_3_cast_reg_690[2] <= tmp_3_cast_fu_470_p3[2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln45_reg_708 <= add_ln45_fu_516_p2;
        pollMatrix_addr_reg_713 <= zext_ln46_fu_527_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        currentPoint_int_V_0_06_reg_176 <= currentPoint_int_V_1_1_reg_625;
        currentPoint_int_V_1_07_reg_164 <= currentPoint_int_V_1_reg_620;
        mesh_V_0_08_reg_152 <= mesh_V_1_2_fu_375_p3;
        mesh_V_1_09_reg_140 <= mesh_V_1_1_fu_368_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_fu_283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        currentPoint_int_V_1_1_reg_625 <= currentPoint_int_V_1_1_fu_300_p3;
        currentPoint_int_V_1_reg_620 <= currentPoint_int_V_1_fu_293_p3;
        ret_reg_636 <= ret_fu_317_p2;
        rhs_reg_630 <= rhs_fu_307_p3;
        trunc_ln20_reg_614 <= trunc_ln20_fu_289_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln44_fu_478_p2 == 1'd0))) begin
        lhs_reg_703[25 : 8] <= lhs_fu_508_p3[25 : 8];
        r_V_3_reg_698 <= r_V_3_fu_492_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        r_V_4_reg_731 <= r_V_4_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln42_fu_436_p2 == 1'd0))) begin
        randomVector_V_0_05_reg_199 <= randomVector_V_1_fu_446_p3;
        randomVector_V_1_04_reg_211 <= randomVector_V_1_1_fu_453_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_3_reg_726 <= directions_q0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln44_fu_478_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln44_fu_478_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        directions_address0 = zext_ln46_fu_527_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        directions_address0 = grp_generatePollDirections_fu_256_directions_address0;
    end else begin
        directions_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        directions_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        directions_ce0 = grp_generatePollDirections_fu_256_directions_ce0;
    end else begin
        directions_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        directions_ce1 = grp_generatePollDirections_fu_256_directions_ce1;
    end else begin
        directions_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        directions_we0 = grp_generatePollDirections_fu_256_directions_we0;
    end else begin
        directions_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        directions_we1 = grp_generatePollDirections_fu_256_directions_we1;
    end else begin
        directions_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        pollMatrix_ce0 = 1'b1;
    end else begin
        pollMatrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        pollMatrix_we0 = 1'b1;
    end else begin
        pollMatrix_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln19_fu_283_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln42_fu_436_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_generatePollDirections_fu_256_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln44_fu_478_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln45_fu_533_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_fu_277_p2 = (i_reg_188 + 2'd1);

assign add_ln42_fu_430_p2 = (i_1_reg_223 + 2'd1);

assign add_ln44_fu_460_p2 = (i_2_reg_234 + 2'd1);

assign add_ln45_fu_516_p2 = (j_reg_245 + 3'd1);

assign add_ln46_fu_522_p2 = (tmp_3_cast_reg_690 + j_reg_245);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign currentPoint_int_V_1_1_fu_300_p3 = ((trunc_ln20_fu_289_p1[0:0] == 1'b1) ? currentPoint_int_V_0_06_reg_176 : optimum_V_0);

assign currentPoint_int_V_1_fu_293_p3 = ((trunc_ln20_fu_289_p1[0:0] == 1'b1) ? optimum_V_1 : currentPoint_int_V_1_07_reg_164);

assign empty_53_fu_484_p1 = mesh_V_1_09_reg_140[25:0];

assign empty_54_fu_488_p1 = mesh_V_0_08_reg_152[25:0];

assign empty_55_fu_500_p3 = ((trunc_ln46_fu_466_p1[0:0] == 1'b1) ? currentPoint_int_V_1_07_reg_164 : currentPoint_int_V_0_06_reg_176);

assign grp_fu_562_p1 = 20'd27;

assign grp_fu_570_p1 = 20'd27;

assign grp_generatePollDirections_fu_256_ap_start = grp_generatePollDirections_fu_256_ap_start_reg;

assign icmp_ln19_fu_283_p2 = ((i_reg_188 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_436_p2 = ((i_1_reg_223 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_478_p2 = ((i_2_reg_234 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_533_p2 = ((j_reg_245 == 3'd4) ? 1'b1 : 1'b0);

assign lhs_fu_508_p3 = {{empty_55_fu_500_p3}, {8'd0}};

assign mesh_V_1_1_fu_368_p3 = ((trunc_ln20_reg_614[0:0] == 1'b1) ? r_V_5_fu_360_p3 : mesh_V_1_09_reg_140);

assign mesh_V_1_2_fu_375_p3 = ((trunc_ln20_reg_614[0:0] == 1'b1) ? mesh_V_0_08_reg_152 : r_V_5_fu_360_p3);

assign pollMatrix_address0 = pollMatrix_addr_reg_713;

assign pollMatrix_d0 = {{ret_V_fu_547_p2[25:8]}};

assign r_V_1_fu_354_p2 = 36'd16777216 << sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1;

assign r_V_3_fu_492_p3 = ((trunc_ln46_fu_466_p1[0:0] == 1'b1) ? empty_53_fu_484_p1 : empty_54_fu_488_p1);

assign r_V_5_fu_360_p3 = ((tmp_2_fu_331_p3[0:0] == 1'b1) ? r_V_fu_341_p2 : r_V_1_fu_354_p2);

assign r_V_fu_341_p2 = 36'd16777216 >> sh_prom_i_i_i54_fu_338_p1;

assign randomVector_V_1_1_fu_453_p3 = ((trunc_ln43_fu_442_p1[0:0] == 1'b1) ? sext_ln708_1_reg_662 : randomVector_V_1_04_reg_211);

assign randomVector_V_1_fu_446_p3 = ((trunc_ln43_fu_442_p1[0:0] == 1'b1) ? randomVector_V_0_05_reg_199 : sext_ln708_reg_657);

assign ret_V_fu_547_p2 = (lhs_reg_703 + r_V_4_reg_731);

assign ret_fu_317_p2 = ($signed(7'd0) - $signed(sext_ln215_fu_313_p1));

assign rhs_fu_307_p3 = ((trunc_ln20_fu_289_p1[0:0] == 1'b1) ? p_read3 : p_read2);

assign sext_ln215_fu_313_p1 = rhs_fu_307_p3;

assign sext_ln708_1_fu_426_p1 = $signed(v_V_1_fu_420_p2);

assign sext_ln708_fu_402_p1 = $signed(v_V_0_fu_396_p2);

assign sh_prom_i_i_i54_fu_338_p1 = ret_reg_636;

assign sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1 = $unsigned(sh_prom_i_i_i_cast_cast_cast_fu_347_p1);

assign sh_prom_i_i_i_cast_cast_cast_fu_347_p1 = rhs_reg_630;

assign tmp_2_fu_331_p3 = rhs_reg_630[32'd5];

assign tmp_3_cast_fu_470_p3 = {{trunc_ln46_fu_466_p1}, {2'd0}};

assign trunc_ln20_fu_289_p1 = i_reg_188[0:0];

assign trunc_ln43_fu_442_p1 = i_1_reg_223[0:0];

assign trunc_ln46_fu_466_p1 = i_2_reg_234[0:0];

assign trunc_ln708_1_fu_387_p4 = {{grp_fu_562_p2[19:4]}};

assign trunc_ln708_2_fu_411_p4 = {{grp_fu_570_p2[19:4]}};

assign v_V_0_fu_396_p2 = (trunc_ln708_1_fu_387_p4 ^ 16'd32768);

assign v_V_1_fu_420_p2 = (trunc_ln708_2_fu_411_p4 ^ 16'd32768);

assign zext_ln46_fu_527_p1 = add_ln46_fu_522_p2;

always @ (posedge ap_clk) begin
    tmp_3_cast_reg_690[1:0] <= 2'b00;
    lhs_reg_703[7:0] <= 8'b00000000;
end

endmodule //MPCwithMADS_generatePollMatrix
