// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MPCwithMADS_generatePollDirections (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        directions_address0,
        directions_ce0,
        directions_we0,
        directions_d0,
        directions_address1,
        directions_ce1,
        directions_we1,
        directions_d1
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] p_read;
input  [17:0] p_read1;
input  [5:0] p_read2;
input  [5:0] p_read3;
input  [5:0] p_read4;
input  [5:0] p_read5;
output  [2:0] directions_address0;
output   directions_ce0;
output   directions_we0;
output  [11:0] directions_d0;
output  [2:0] directions_address1;
output   directions_ce1;
output   directions_we1;
output  [11:0] directions_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg directions_ce0;
reg directions_we0;
reg directions_ce1;
reg directions_we1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] add_ln18_fu_347_p2;
reg   [1:0] add_ln18_reg_1287;
wire    ap_CS_fsm_state2;
wire   [0:0] trunc_ln215_fu_359_p1;
reg   [0:0] trunc_ln215_reg_1295;
wire   [0:0] icmp_ln18_fu_353_p2;
wire  signed [6:0] sext_ln1380_fu_387_p1;
reg  signed [6:0] sext_ln1380_reg_1301;
reg   [0:0] isNeg_reg_1306;
wire   [6:0] sub_ln1357_fu_399_p2;
reg   [6:0] sub_ln1357_reg_1312;
wire   [35:0] mesh_V_1_3_fu_442_p3;
wire    ap_CS_fsm_state3;
wire   [35:0] mesh_V_1_4_fu_449_p3;
wire   [1:0] add_ln62_fu_456_p2;
reg   [1:0] add_ln62_reg_1352;
wire    ap_CS_fsm_state4;
wire   [0:0] empty_58_fu_468_p1;
reg   [0:0] empty_58_reg_1360;
wire   [0:0] icmp_ln62_fu_462_p2;
wire  signed [32:0] sext_ln1115_fu_496_p1;
reg  signed [32:0] sext_ln1115_reg_1371;
wire   [1:0] add_ln63_fu_520_p2;
reg   [1:0] add_ln63_reg_1428;
wire    ap_CS_fsm_state5;
wire   [0:0] trunc_ln1118_fu_532_p1;
reg   [0:0] trunc_ln1118_reg_1436;
wire   [0:0] icmp_ln63_fu_526_p2;
wire   [0:0] icmp_ln65_fu_546_p2;
reg   [0:0] icmp_ln65_reg_1449;
wire   [17:0] H_1_1_V_24_fu_651_p3;
reg   [17:0] H_1_1_V_24_reg_1455;
wire    ap_CS_fsm_state8;
wire   [1:0] add_ln34_fu_677_p2;
reg   [1:0] add_ln34_reg_1460;
wire    ap_CS_fsm_state10;
wire   [0:0] empty_62_fu_689_p1;
reg   [0:0] empty_62_reg_1468;
wire   [0:0] icmp_ln34_fu_683_p2;
wire   [50:0] zext_ln35_fu_701_p1;
reg   [50:0] zext_ln35_reg_1479;
wire   [0:0] sel_tmp30_fu_705_p2;
reg   [0:0] sel_tmp30_reg_1484;
wire   [1:0] add_ln35_fu_711_p2;
reg   [1:0] add_ln35_reg_1489;
wire    ap_CS_fsm_state11;
wire   [0:0] trunc_ln1494_fu_735_p1;
reg   [0:0] trunc_ln1494_reg_1497;
wire   [0:0] icmp_ln35_fu_717_p2;
wire   [17:0] H_V_1_1_9_fu_872_p3;
reg   [17:0] H_V_1_1_9_reg_1505;
wire   [17:0] H_V_1_0_7_fu_888_p3;
reg   [17:0] H_V_1_0_7_reg_1510;
wire   [17:0] H_V_0_1_7_fu_931_p3;
reg   [17:0] H_V_0_1_7_reg_1515;
wire   [17:0] H_V_0_0_9_fu_963_p3;
reg   [17:0] H_V_0_0_9_reg_1520;
wire   [15:0] empty_65_fu_1001_p3;
reg  signed [15:0] empty_65_reg_1525;
wire    ap_CS_fsm_state12;
wire   [50:0] grp_fu_1012_p2;
reg   [50:0] r_V_12_reg_1535;
wire    ap_CS_fsm_state13;
wire   [53:0] grp_round_fixed_54_15_s_fu_318_ap_return;
reg   [53:0] p_Val2_s_reg_1540;
wire    ap_CS_fsm_state15;
reg   [11:0] ret_V_cast_reg_1545;
wire   [0:0] icmp_ln851_fu_1047_p2;
reg   [0:0] icmp_ln851_reg_1552;
wire   [1:0] add_ln45_fu_1154_p2;
reg   [1:0] add_ln45_reg_1557;
wire    ap_CS_fsm_state17;
wire   [0:0] trunc_ln47_fu_1166_p1;
reg   [0:0] trunc_ln47_reg_1565;
wire   [0:0] icmp_ln45_fu_1160_p2;
wire   [1:0] add_ln46_fu_1170_p2;
wire    ap_CS_fsm_state18;
reg   [35:0] mesh_V_1_011_reg_215;
reg   [35:0] mesh_V_0_010_reg_227;
reg   [1:0] i_reg_239;
reg   [1:0] i_3_reg_250;
reg   [1:0] j_reg_262;
wire    ap_CS_fsm_state9;
reg   [1:0] i_4_reg_273;
reg   [1:0] j_1_reg_284;
wire    ap_CS_fsm_state16;
reg   [1:0] i_5_reg_295;
wire   [0:0] icmp_ln46_fu_1189_p2;
reg   [1:0] j_2_reg_307;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln47_fu_1184_p1;
wire   [63:0] zext_ln48_fu_1244_p1;
reg   [17:0] H_1_1_V_1_fu_106;
reg   [17:0] H_1_1_V_9_fu_110;
wire   [17:0] H_1_1_V_7_fu_603_p3;
reg   [17:0] H_1_1_V_14_fu_114;
wire   [17:0] H_1_1_V_6_fu_596_p3;
reg   [17:0] H_1_1_V_15_fu_118;
wire   [17:0] H_1_1_V_23_fu_644_p3;
reg   [17:0] H_V_0_0_5_fu_122;
reg   [17:0] H_V_0_1_3_fu_126;
reg   [17:0] H_V_1_0_3_fu_130;
reg   [17:0] H_V_1_1_5_fu_134;
reg   [11:0] B_V_1_1_1_fu_138;
wire   [11:0] B_V_1_1_8_fu_1127_p3;
reg   [11:0] B_V_1_1_9_fu_142;
wire   [11:0] B_V_1_1_7_fu_1120_p3;
reg   [11:0] B_V_1_1_10_fu_146;
wire   [11:0] B_V_1_1_6_fu_1113_p3;
reg   [11:0] B_V_1_1_11_fu_150;
wire   [11:0] B_V_1_1_5_fu_1106_p3;
wire   [11:0] select_ln47_2_fu_1215_p3;
wire   [5:0] select_ln215_fu_363_p3;
wire   [5:0] select_ln215_1_fu_369_p3;
wire   [5:0] sub_ln69_fu_375_p2;
wire  signed [5:0] frameMeshDiff_V_fu_381_p2;
wire   [6:0] ush_fu_410_p3;
wire  signed [31:0] sh_prom_i_i_i_cast_cast_cast_fu_415_p1;
wire   [35:0] sh_prom_i_i_i_cast_cast_cast_cast_fu_419_p1;
wire   [35:0] r_V_fu_423_p2;
wire   [35:0] r_V_6_fu_429_p2;
wire   [35:0] r_V_11_fu_435_p3;
wire   [17:0] empty_59_fu_472_p3;
wire   [18:0] p_shl_fu_478_p3;
wire  signed [19:0] p_shl_cast_fu_486_p1;
wire   [19:0] r_V_8_fu_490_p2;
wire  signed [17:0] select_ln1118_fu_536_p3;
wire  signed [32:0] grp_fu_1249_p2;
wire   [17:0] H_1_0_V_fu_552_p4;
wire   [17:0] H_1_1_V_17_fu_561_p3;
wire   [17:0] H_1_1_V_18_fu_568_p3;
wire   [17:0] H_1_1_V_fu_575_p3;
wire   [17:0] H_1_1_V_19_fu_582_p3;
wire   [17:0] select_ln703_fu_617_p3;
wire   [17:0] H_0_0_V_fu_624_p2;
wire   [17:0] H_1_1_V_21_fu_630_p3;
wire   [17:0] H_1_1_V_5_fu_589_p3;
wire   [17:0] H_1_1_V_22_fu_637_p3;
wire   [17:0] H_1_1_V_8_fu_610_p3;
wire   [35:0] r_V_9_fu_693_p3;
wire   [17:0] select_ln1494_1_fu_739_p3;
wire   [17:0] select_ln1494_fu_747_p3;
wire   [17:0] phi_ln1494_fu_755_p3;
wire   [0:0] icmp_ln1494_fu_766_p2;
wire   [0:0] sel_tmp7_fu_842_p2;
wire   [17:0] select_ln37_2_fu_778_p3;
wire   [0:0] xor_ln1494_fu_855_p2;
wire   [0:0] tmp_fu_861_p2;
wire   [0:0] icmp_ln1495_fu_772_p2;
wire   [0:0] sel_tmp11_fu_866_p2;
wire   [17:0] select_ln39_2_fu_810_p3;
wire   [17:0] sel_tmp8_fu_847_p3;
wire   [17:0] select_ln37_3_fu_786_p3;
wire   [17:0] select_ln39_3_fu_818_p3;
wire   [17:0] sel_tmp21_fu_880_p3;
wire   [0:0] or_ln1495_fu_896_p2;
wire   [17:0] select_ln39_fu_826_p3;
wire   [0:0] sel_tmp31_fu_910_p2;
wire   [17:0] select_ln37_fu_794_p3;
wire   [17:0] select_ln1495_fu_902_p3;
wire   [17:0] sel_tmp32_fu_915_p3;
wire   [17:0] sel_tmp34_fu_923_p3;
wire   [17:0] select_ln39_1_fu_834_p3;
wire   [17:0] select_ln37_1_fu_802_p3;
wire   [17:0] select_ln1495_1_fu_939_p3;
wire   [17:0] sel_tmp45_fu_947_p3;
wire   [17:0] sel_tmp47_fu_955_p3;
wire   [15:0] sel_tmp55_fu_971_p3;
wire   [15:0] trunc_ln1494_1_fu_762_p1;
wire   [0:0] empty_64_fu_995_p2;
wire   [15:0] sel_tmp60_fu_987_p3;
wire   [15:0] sel_tmp58_fu_979_p3;
wire   [35:0] grp_fu_1012_p0;
wire   [38:0] trunc_ln851_fu_1043_p1;
wire   [11:0] ret_V_fu_1060_p2;
wire   [0:0] p_Result_s_fu_1053_p3;
wire   [11:0] select_ln850_fu_1065_p3;
wire   [11:0] ret_V_2_fu_1071_p3;
wire   [11:0] B_V_1_1_13_fu_1078_p3;
wire   [11:0] B_V_1_1_14_fu_1085_p3;
wire   [11:0] B_V_1_1_fu_1092_p3;
wire   [11:0] B_V_1_1_15_fu_1099_p3;
wire   [3:0] tmp_7_fu_1176_p3;
wire   [0:0] trunc_ln47_1_fu_1195_p1;
wire   [11:0] select_ln47_1_fu_1199_p3;
wire   [11:0] select_ln47_fu_1207_p3;
wire   [1:0] xor_ln48_fu_1230_p2;
wire   [3:0] tmp_8_fu_1236_p3;
wire  signed [19:0] grp_fu_1249_p0;
reg   [17:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
end

MPCwithMADS_round_fixed_54_15_s grp_round_fixed_54_15_s_fu_318(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(r_V_12_reg_1535),
    .ap_return(grp_round_fixed_54_15_s_fu_318_ap_return)
);

MPCwithMADS_mul_36ns_16s_51_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 51 ))
mul_36ns_16s_51_2_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1012_p0),
    .din1(empty_65_reg_1525),
    .ce(1'b1),
    .dout(grp_fu_1012_p2)
);

MPCwithMADS_mul_mul_20s_18s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 33 ))
mul_mul_20s_18s_33_4_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1249_p0),
    .din1(select_ln1118_fu_536_p3),
    .ce(1'b1),
    .dout(grp_fu_1249_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_353_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        H_1_1_V_1_fu_106 <= 18'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        H_1_1_V_1_fu_106 <= H_1_1_V_24_reg_1455;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
        H_V_0_0_5_fu_122 <= H_1_1_V_1_fu_106;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_0_0_5_fu_122 <= H_V_0_0_9_reg_1520;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
        H_V_0_1_3_fu_126 <= H_1_1_V_9_fu_110;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_0_1_3_fu_126 <= H_V_0_1_7_reg_1515;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
        H_V_1_0_3_fu_130 <= H_1_1_V_14_fu_114;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_1_0_3_fu_130 <= H_V_1_0_7_reg_1510;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
        H_V_1_1_5_fu_134 <= H_1_1_V_15_fu_118;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_1_1_5_fu_134 <= H_V_1_1_9_reg_1505;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_353_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_3_reg_250 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln63_fu_526_p2 == 1'd1))) begin
        i_3_reg_250 <= add_ln62_reg_1352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
        i_4_reg_273 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln35_fu_717_p2 == 1'd1))) begin
        i_4_reg_273 <= add_ln34_reg_1460;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln34_fu_683_p2 == 1'd1))) begin
        i_5_reg_295 <= 2'd0;
    end else if (((icmp_ln46_fu_1189_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        i_5_reg_295 <= add_ln45_reg_1557;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_239 <= add_ln18_reg_1287;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_239 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        j_1_reg_284 <= add_ln35_reg_1489;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln34_fu_683_p2 == 1'd0))) begin
        j_1_reg_284 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln45_fu_1160_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        j_2_reg_307 <= 2'd0;
    end else if (((icmp_ln46_fu_1189_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        j_2_reg_307 <= add_ln46_fu_1170_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        j_reg_262 <= add_ln63_reg_1428;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd0))) begin
        j_reg_262 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        B_V_1_1_10_fu_146 <= B_V_1_1_6_fu_1113_p3;
        B_V_1_1_11_fu_150 <= B_V_1_1_5_fu_1106_p3;
        B_V_1_1_1_fu_138 <= B_V_1_1_8_fu_1127_p3;
        B_V_1_1_9_fu_142 <= B_V_1_1_7_fu_1120_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        H_1_1_V_14_fu_114 <= H_1_1_V_6_fu_596_p3;
        H_1_1_V_15_fu_118 <= H_1_1_V_23_fu_644_p3;
        H_1_1_V_24_reg_1455 <= H_1_1_V_24_fu_651_p3;
        H_1_1_V_9_fu_110 <= H_1_1_V_7_fu_603_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln35_fu_717_p2 == 1'd0))) begin
        H_V_0_0_9_reg_1520 <= H_V_0_0_9_fu_963_p3;
        H_V_0_1_7_reg_1515 <= H_V_0_1_7_fu_931_p3;
        H_V_1_0_7_reg_1510 <= H_V_1_0_7_fu_888_p3;
        H_V_1_1_9_reg_1505 <= H_V_1_1_9_fu_872_p3;
        empty_65_reg_1525 <= empty_65_fu_1001_p3;
        trunc_ln1494_reg_1497 <= trunc_ln1494_fu_735_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln18_reg_1287 <= add_ln18_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln34_reg_1460 <= add_ln34_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln35_reg_1489 <= add_ln35_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln45_reg_1557 <= add_ln45_fu_1154_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln62_reg_1352 <= add_ln62_fu_456_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln63_reg_1428 <= add_ln63_fu_520_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd0))) begin
        empty_58_reg_1360 <= empty_58_fu_468_p1;
        sext_ln1115_reg_1371[32 : 1] <= sext_ln1115_fu_496_p1[32 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln34_fu_683_p2 == 1'd0))) begin
        empty_62_reg_1468 <= empty_62_fu_689_p1;
        sel_tmp30_reg_1484 <= sel_tmp30_fu_705_p2;
        zext_ln35_reg_1479[35 : 0] <= zext_ln35_fu_701_p1[35 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln63_fu_526_p2 == 1'd0))) begin
        icmp_ln65_reg_1449 <= icmp_ln65_fu_546_p2;
        trunc_ln1118_reg_1436 <= trunc_ln1118_fu_532_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln851_reg_1552 <= icmp_ln851_fu_1047_p2;
        p_Val2_s_reg_1540 <= grp_round_fixed_54_15_s_fu_318_ap_return;
        ret_V_cast_reg_1545 <= {{grp_round_fixed_54_15_s_fu_318_ap_return[50:39]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_353_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        isNeg_reg_1306 <= frameMeshDiff_V_fu_381_p2[32'd5];
        sext_ln1380_reg_1301 <= sext_ln1380_fu_387_p1;
        sub_ln1357_reg_1312 <= sub_ln1357_fu_399_p2;
        trunc_ln215_reg_1295 <= trunc_ln215_fu_359_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mesh_V_0_010_reg_227 <= mesh_V_1_4_fu_449_p3;
        mesh_V_1_011_reg_215 <= mesh_V_1_3_fu_442_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        r_V_12_reg_1535 <= grp_fu_1012_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln45_fu_1160_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        trunc_ln47_reg_1565 <= trunc_ln47_fu_1166_p1;
    end
end

always @ (*) begin
    if ((((icmp_ln45_fu_1160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln45_fu_1160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        directions_ce0 = 1'b1;
    end else begin
        directions_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        directions_ce1 = 1'b1;
    end else begin
        directions_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_1189_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        directions_we0 = 1'b1;
    end else begin
        directions_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_1189_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        directions_we1 = 1'b1;
    end else begin
        directions_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln18_fu_353_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln62_fu_462_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln63_fu_526_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln34_fu_683_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln35_fu_717_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln45_fu_1160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln46_fu_1189_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_V_1_1_13_fu_1078_p3 = ((trunc_ln1494_reg_1497[0:0] == 1'b1) ? ret_V_2_fu_1071_p3 : B_V_1_1_11_fu_150);

assign B_V_1_1_14_fu_1085_p3 = ((trunc_ln1494_reg_1497[0:0] == 1'b1) ? B_V_1_1_10_fu_146 : ret_V_2_fu_1071_p3);

assign B_V_1_1_15_fu_1099_p3 = ((trunc_ln1494_reg_1497[0:0] == 1'b1) ? B_V_1_1_1_fu_138 : ret_V_2_fu_1071_p3);

assign B_V_1_1_5_fu_1106_p3 = ((empty_62_reg_1468[0:0] == 1'b1) ? B_V_1_1_13_fu_1078_p3 : B_V_1_1_11_fu_150);

assign B_V_1_1_6_fu_1113_p3 = ((empty_62_reg_1468[0:0] == 1'b1) ? B_V_1_1_14_fu_1085_p3 : B_V_1_1_10_fu_146);

assign B_V_1_1_7_fu_1120_p3 = ((empty_62_reg_1468[0:0] == 1'b1) ? B_V_1_1_9_fu_142 : B_V_1_1_fu_1092_p3);

assign B_V_1_1_8_fu_1127_p3 = ((empty_62_reg_1468[0:0] == 1'b1) ? B_V_1_1_1_fu_138 : B_V_1_1_15_fu_1099_p3);

assign B_V_1_1_fu_1092_p3 = ((trunc_ln1494_reg_1497[0:0] == 1'b1) ? ret_V_2_fu_1071_p3 : B_V_1_1_9_fu_142);

assign H_0_0_V_fu_624_p2 = (select_ln703_fu_617_p3 + 18'd32768);

assign H_1_0_V_fu_552_p4 = {{grp_fu_1249_p2[32:15]}};

assign H_1_1_V_17_fu_561_p3 = ((trunc_ln1118_reg_1436[0:0] == 1'b1) ? H_1_0_V_fu_552_p4 : H_1_1_V_15_fu_118);

assign H_1_1_V_18_fu_568_p3 = ((trunc_ln1118_reg_1436[0:0] == 1'b1) ? H_1_1_V_14_fu_114 : H_1_0_V_fu_552_p4);

assign H_1_1_V_19_fu_582_p3 = ((trunc_ln1118_reg_1436[0:0] == 1'b1) ? H_1_1_V_1_fu_106 : H_1_0_V_fu_552_p4);

assign H_1_1_V_21_fu_630_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_0_0_V_fu_624_p2 : H_1_1_V_15_fu_118);

assign H_1_1_V_22_fu_637_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_1_fu_106 : H_0_0_V_fu_624_p2);

assign H_1_1_V_23_fu_644_p3 = ((icmp_ln65_reg_1449[0:0] == 1'b1) ? H_1_1_V_21_fu_630_p3 : H_1_1_V_5_fu_589_p3);

assign H_1_1_V_24_fu_651_p3 = ((icmp_ln65_reg_1449[0:0] == 1'b1) ? H_1_1_V_22_fu_637_p3 : H_1_1_V_8_fu_610_p3);

assign H_1_1_V_5_fu_589_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_17_fu_561_p3 : H_1_1_V_15_fu_118);

assign H_1_1_V_6_fu_596_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_18_fu_568_p3 : H_1_1_V_14_fu_114);

assign H_1_1_V_7_fu_603_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_9_fu_110 : H_1_1_V_fu_575_p3);

assign H_1_1_V_8_fu_610_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_1_fu_106 : H_1_1_V_19_fu_582_p3);

assign H_1_1_V_fu_575_p3 = ((trunc_ln1118_reg_1436[0:0] == 1'b1) ? H_1_0_V_fu_552_p4 : H_1_1_V_9_fu_110);

assign H_V_0_0_9_fu_963_p3 = ((sel_tmp11_fu_866_p2[0:0] == 1'b1) ? H_V_0_0_5_fu_122 : sel_tmp47_fu_955_p3);

assign H_V_0_1_7_fu_931_p3 = ((sel_tmp11_fu_866_p2[0:0] == 1'b1) ? H_V_0_1_3_fu_126 : sel_tmp34_fu_923_p3);

assign H_V_1_0_7_fu_888_p3 = ((sel_tmp11_fu_866_p2[0:0] == 1'b1) ? select_ln39_3_fu_818_p3 : sel_tmp21_fu_880_p3);

assign H_V_1_1_9_fu_872_p3 = ((sel_tmp11_fu_866_p2[0:0] == 1'b1) ? select_ln39_2_fu_810_p3 : sel_tmp8_fu_847_p3);

assign add_ln18_fu_347_p2 = (i_reg_239 + 2'd1);

assign add_ln34_fu_677_p2 = (i_4_reg_273 + 2'd1);

assign add_ln35_fu_711_p2 = (j_1_reg_284 + 2'd1);

assign add_ln45_fu_1154_p2 = (i_5_reg_295 + 2'd1);

assign add_ln46_fu_1170_p2 = (j_2_reg_307 + 2'd1);

assign add_ln62_fu_456_p2 = (i_3_reg_250 + 2'd1);

assign add_ln63_fu_520_p2 = (j_reg_262 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign directions_address0 = zext_ln48_fu_1244_p1;

assign directions_address1 = zext_ln47_fu_1184_p1;

assign directions_d0 = (12'd0 - select_ln47_2_fu_1215_p3);

assign directions_d1 = select_ln47_2_fu_1215_p3;

assign empty_58_fu_468_p1 = i_3_reg_250[0:0];

assign empty_59_fu_472_p3 = ((empty_58_fu_468_p1[0:0] == 1'b1) ? p_read1 : p_read);

assign empty_62_fu_689_p1 = i_4_reg_273[0:0];

assign empty_64_fu_995_p2 = (sel_tmp7_fu_842_p2 | sel_tmp11_fu_866_p2);

assign empty_65_fu_1001_p3 = ((empty_64_fu_995_p2[0:0] == 1'b1) ? sel_tmp60_fu_987_p3 : sel_tmp58_fu_979_p3);

assign frameMeshDiff_V_fu_381_p2 = (sub_ln69_fu_375_p2 + 6'd1);

assign grp_fu_1012_p0 = zext_ln35_reg_1479;

assign grp_fu_1249_p0 = sext_ln1115_reg_1371;

assign icmp_ln1494_fu_766_p2 = (($signed(phi_ln1494_fu_755_p3) > $signed(18'd16384)) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_772_p2 = (($signed(phi_ln1494_fu_755_p3) < $signed(18'd245760)) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_353_p2 = ((i_reg_239 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_683_p2 = ((i_4_reg_273 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_717_p2 = ((j_1_reg_284 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1160_p2 = ((i_5_reg_295 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_1189_p2 = ((j_2_reg_307 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_462_p2 = ((i_3_reg_250 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_526_p2 = ((j_reg_262 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_546_p2 = ((i_3_reg_250 == j_reg_262) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_1047_p2 = ((trunc_ln851_fu_1043_p1 == 39'd0) ? 1'b1 : 1'b0);

assign mesh_V_1_3_fu_442_p3 = ((trunc_ln215_reg_1295[0:0] == 1'b1) ? r_V_11_fu_435_p3 : mesh_V_1_011_reg_215);

assign mesh_V_1_4_fu_449_p3 = ((trunc_ln215_reg_1295[0:0] == 1'b1) ? mesh_V_0_010_reg_227 : r_V_11_fu_435_p3);

assign or_ln1495_fu_896_p2 = (icmp_ln1495_fu_772_p2 | icmp_ln1494_fu_766_p2);

assign p_Result_s_fu_1053_p3 = p_Val2_s_reg_1540[32'd53];

assign p_shl_cast_fu_486_p1 = $signed(p_shl_fu_478_p3);

assign p_shl_fu_478_p3 = {{empty_59_fu_472_p3}, {1'd0}};

assign phi_ln1494_fu_755_p3 = ((empty_62_reg_1468[0:0] == 1'b1) ? select_ln1494_1_fu_739_p3 : select_ln1494_fu_747_p3);

assign r_V_11_fu_435_p3 = ((isNeg_reg_1306[0:0] == 1'b1) ? r_V_fu_423_p2 : r_V_6_fu_429_p2);

assign r_V_6_fu_429_p2 = 36'd16777216 << sh_prom_i_i_i_cast_cast_cast_cast_fu_419_p1;

assign r_V_8_fu_490_p2 = ($signed(20'd0) - $signed(p_shl_cast_fu_486_p1));

assign r_V_9_fu_693_p3 = ((empty_62_fu_689_p1[0:0] == 1'b1) ? mesh_V_1_011_reg_215 : mesh_V_0_010_reg_227);

assign r_V_fu_423_p2 = 36'd16777216 >> sh_prom_i_i_i_cast_cast_cast_cast_fu_419_p1;

assign ret_V_2_fu_1071_p3 = ((p_Result_s_fu_1053_p3[0:0] == 1'b1) ? select_ln850_fu_1065_p3 : ret_V_cast_reg_1545);

assign ret_V_fu_1060_p2 = (ret_V_cast_reg_1545 + 12'd1);

assign sel_tmp11_fu_866_p2 = (tmp_fu_861_p2 & icmp_ln1495_fu_772_p2);

assign sel_tmp21_fu_880_p3 = ((sel_tmp7_fu_842_p2[0:0] == 1'b1) ? select_ln37_3_fu_786_p3 : H_V_1_0_3_fu_130);

assign sel_tmp30_fu_705_p2 = (empty_62_fu_689_p1 ^ 1'd1);

assign sel_tmp31_fu_910_p2 = (sel_tmp30_reg_1484 & icmp_ln1494_fu_766_p2);

assign sel_tmp32_fu_915_p3 = ((sel_tmp31_fu_910_p2[0:0] == 1'b1) ? select_ln37_fu_794_p3 : select_ln1495_fu_902_p3);

assign sel_tmp34_fu_923_p3 = ((sel_tmp7_fu_842_p2[0:0] == 1'b1) ? H_V_0_1_3_fu_126 : sel_tmp32_fu_915_p3);

assign sel_tmp45_fu_947_p3 = ((sel_tmp31_fu_910_p2[0:0] == 1'b1) ? select_ln37_1_fu_802_p3 : select_ln1495_1_fu_939_p3);

assign sel_tmp47_fu_955_p3 = ((sel_tmp7_fu_842_p2[0:0] == 1'b1) ? H_V_0_0_5_fu_122 : sel_tmp45_fu_947_p3);

assign sel_tmp55_fu_971_p3 = ((sel_tmp31_fu_910_p2[0:0] == 1'b1) ? 16'd16384 : 16'd49152);

assign sel_tmp58_fu_979_p3 = ((or_ln1495_fu_896_p2[0:0] == 1'b1) ? sel_tmp55_fu_971_p3 : trunc_ln1494_1_fu_762_p1);

assign sel_tmp60_fu_987_p3 = ((sel_tmp11_fu_866_p2[0:0] == 1'b1) ? 16'd49152 : 16'd16384);

assign sel_tmp7_fu_842_p2 = (icmp_ln1494_fu_766_p2 & empty_62_reg_1468);

assign sel_tmp8_fu_847_p3 = ((sel_tmp7_fu_842_p2[0:0] == 1'b1) ? select_ln37_2_fu_778_p3 : H_V_1_1_5_fu_134);

assign select_ln1118_fu_536_p3 = ((trunc_ln1118_fu_532_p1[0:0] == 1'b1) ? p_read1 : p_read);

assign select_ln1494_1_fu_739_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_1_1_5_fu_134 : H_V_1_0_3_fu_130);

assign select_ln1494_fu_747_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_0_1_3_fu_126 : H_V_0_0_5_fu_122);

assign select_ln1495_1_fu_939_p3 = ((or_ln1495_fu_896_p2[0:0] == 1'b1) ? select_ln39_1_fu_834_p3 : H_V_0_0_5_fu_122);

assign select_ln1495_fu_902_p3 = ((or_ln1495_fu_896_p2[0:0] == 1'b1) ? select_ln39_fu_826_p3 : H_V_0_1_3_fu_126);

assign select_ln215_1_fu_369_p3 = ((trunc_ln215_fu_359_p1[0:0] == 1'b1) ? p_read5 : p_read4);

assign select_ln215_fu_363_p3 = ((trunc_ln215_fu_359_p1[0:0] == 1'b1) ? p_read3 : p_read2);

assign select_ln37_1_fu_802_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_0_0_5_fu_122 : 18'd16384);

assign select_ln37_2_fu_778_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? 18'd16384 : H_V_1_1_5_fu_134);

assign select_ln37_3_fu_786_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_1_0_3_fu_130 : 18'd16384);

assign select_ln37_fu_794_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? 18'd16384 : H_V_0_1_3_fu_126);

assign select_ln39_1_fu_834_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_0_0_5_fu_122 : 18'd245760);

assign select_ln39_2_fu_810_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? 18'd245760 : H_V_1_1_5_fu_134);

assign select_ln39_3_fu_818_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? H_V_1_0_3_fu_130 : 18'd245760);

assign select_ln39_fu_826_p3 = ((trunc_ln1494_fu_735_p1[0:0] == 1'b1) ? 18'd245760 : H_V_0_1_3_fu_126);

assign select_ln47_1_fu_1199_p3 = ((trunc_ln47_1_fu_1195_p1[0:0] == 1'b1) ? B_V_1_1_11_fu_150 : B_V_1_1_10_fu_146);

assign select_ln47_2_fu_1215_p3 = ((trunc_ln47_reg_1565[0:0] == 1'b1) ? select_ln47_1_fu_1199_p3 : select_ln47_fu_1207_p3);

assign select_ln47_fu_1207_p3 = ((trunc_ln47_1_fu_1195_p1[0:0] == 1'b1) ? B_V_1_1_9_fu_142 : B_V_1_1_1_fu_138);

assign select_ln703_fu_617_p3 = ((empty_58_reg_1360[0:0] == 1'b1) ? H_1_1_V_17_fu_561_p3 : H_1_1_V_19_fu_582_p3);

assign select_ln850_fu_1065_p3 = ((icmp_ln851_reg_1552[0:0] == 1'b1) ? ret_V_cast_reg_1545 : ret_V_fu_1060_p2);

assign sext_ln1115_fu_496_p1 = $signed(r_V_8_fu_490_p2);

assign sext_ln1380_fu_387_p1 = frameMeshDiff_V_fu_381_p2;

assign sh_prom_i_i_i_cast_cast_cast_cast_fu_419_p1 = $unsigned(sh_prom_i_i_i_cast_cast_cast_fu_415_p1);

assign sh_prom_i_i_i_cast_cast_cast_fu_415_p1 = $signed(ush_fu_410_p3);

assign sub_ln1357_fu_399_p2 = ($signed(7'd0) - $signed(sext_ln1380_fu_387_p1));

assign sub_ln69_fu_375_p2 = (select_ln215_fu_363_p3 - select_ln215_1_fu_369_p3);

assign tmp_7_fu_1176_p3 = {{i_5_reg_295}, {j_2_reg_307}};

assign tmp_8_fu_1236_p3 = {{i_5_reg_295}, {xor_ln48_fu_1230_p2}};

assign tmp_fu_861_p2 = (xor_ln1494_fu_855_p2 & empty_62_reg_1468);

assign trunc_ln1118_fu_532_p1 = j_reg_262[0:0];

assign trunc_ln1494_1_fu_762_p1 = phi_ln1494_fu_755_p3[15:0];

assign trunc_ln1494_fu_735_p1 = j_1_reg_284[0:0];

assign trunc_ln215_fu_359_p1 = i_reg_239[0:0];

assign trunc_ln47_1_fu_1195_p1 = j_2_reg_307[0:0];

assign trunc_ln47_fu_1166_p1 = i_5_reg_295[0:0];

assign trunc_ln851_fu_1043_p1 = grp_round_fixed_54_15_s_fu_318_ap_return[38:0];

assign ush_fu_410_p3 = ((isNeg_reg_1306[0:0] == 1'b1) ? sub_ln1357_reg_1312 : sext_ln1380_reg_1301);

assign xor_ln1494_fu_855_p2 = (icmp_ln1494_fu_766_p2 ^ 1'd1);

assign xor_ln48_fu_1230_p2 = (j_2_reg_307 ^ 2'd2);

assign zext_ln35_fu_701_p1 = r_V_9_fu_693_p3;

assign zext_ln47_fu_1184_p1 = tmp_7_fu_1176_p3;

assign zext_ln48_fu_1244_p1 = tmp_8_fu_1236_p3;

always @ (posedge ap_clk) begin
    sext_ln1115_reg_1371[0] <= 1'b0;
    zext_ln35_reg_1479[50:36] <= 15'b000000000000000;
end

endmodule //MPCwithMADS_generatePollDirections
