// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MPCwithMADS_round_fixed_54_15_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [50:0] x;
output  [53:0] ap_return;

wire   [0:0] p_Result_1_fu_64_p3;
reg   [0:0] p_Result_1_reg_117;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [53:0] trunc_ln703_fu_102_p1;
reg   [53:0] trunc_ln703_reg_122;
wire  signed [50:0] x_cast_fu_40_p0;
wire    ap_block_pp0_stage0;
wire  signed [50:0] p_Val2_s_fu_44_p1;
wire   [50:0] p_Val2_s_fu_44_p2;
wire  signed [53:0] sext_ln104_fu_50_p1;
wire  signed [50:0] p_Result_1_fu_64_p1;
wire   [53:0] p_Result_s_fu_54_p4;
wire  signed [53:0] x_cast_fu_40_p1;
wire   [53:0] x_pos_fu_72_p3;
wire   [54:0] zext_ln703_fu_80_p1;
wire   [54:0] ret_V_fu_84_p2;
wire   [54:0] p_Result_3_fu_90_p5;
wire   [53:0] sub_ln703_fu_106_p2;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        p_Result_1_reg_117 <= p_Result_1_fu_64_p1[32'd50];
        trunc_ln703_reg_122 <= trunc_ln703_fu_102_p1;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_1_reg_117[0:0] == 1'b1) ? sub_ln703_fu_106_p2 : trunc_ln703_reg_122);

assign p_Result_1_fu_64_p1 = x;

assign p_Result_1_fu_64_p3 = p_Result_1_fu_64_p1[32'd50];

assign p_Result_3_fu_90_p5 = {{ret_V_fu_84_p2[54:39]}, {39'd0}};

assign p_Result_s_fu_54_p4 = {|(1'd0), sext_ln104_fu_50_p1[53 - 1:0]};

assign p_Val2_s_fu_44_p1 = x;

assign p_Val2_s_fu_44_p2 = ($signed(51'd0) - $signed(p_Val2_s_fu_44_p1));

assign ret_V_fu_84_p2 = (zext_ln703_fu_80_p1 + 55'd274877906944);

assign sext_ln104_fu_50_p1 = $signed(p_Val2_s_fu_44_p2);

assign sub_ln703_fu_106_p2 = (54'd0 - trunc_ln703_reg_122);

assign trunc_ln703_fu_102_p1 = p_Result_3_fu_90_p5[53:0];

assign x_cast_fu_40_p0 = x;

assign x_cast_fu_40_p1 = x_cast_fu_40_p0;

assign x_pos_fu_72_p3 = ((p_Result_1_fu_64_p3[0:0] == 1'b1) ? p_Result_s_fu_54_p4 : x_cast_fu_40_p1);

assign zext_ln703_fu_80_p1 = x_pos_fu_72_p3;

endmodule //MPCwithMADS_round_fixed_54_15_s
