-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MPCwithMADS_generatePollMatrix is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
    pollMatrix_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    pollMatrix_ce0 : OUT STD_LOGIC;
    pollMatrix_we0 : OUT STD_LOGIC;
    pollMatrix_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    optimum_V_0 : IN STD_LOGIC_VECTOR (17 downto 0);
    optimum_V_1 : IN STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of MPCwithMADS_generatePollMatrix is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv36_1000000 : STD_LOGIC_VECTOR (35 downto 0) := "000000000001000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv20_1B : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000011011";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal R1_V : STD_LOGIC_VECTOR (19 downto 0) := "00001001000010100011";
    signal R2_V : STD_LOGIC_VECTOR (19 downto 0) := "01001101011100100001";
    signal add_ln19_fu_277_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln19_reg_606 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln20_fu_289_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_reg_614 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal currentPoint_int_V_1_fu_293_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal currentPoint_int_V_1_reg_620 : STD_LOGIC_VECTOR (17 downto 0);
    signal currentPoint_int_V_1_1_fu_300_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal currentPoint_int_V_1_1_reg_625 : STD_LOGIC_VECTOR (17 downto 0);
    signal rhs_fu_307_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_reg_630 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_fu_317_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_reg_636 : STD_LOGIC_VECTOR (6 downto 0);
    signal mesh_V_1_1_fu_368_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mesh_V_1_2_fu_375_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal sext_ln708_fu_402_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln708_reg_657 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln708_1_fu_426_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln708_1_reg_662 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln42_fu_430_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal randomVector_V_1_fu_446_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln42_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal randomVector_V_1_1_fu_453_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln44_fu_460_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_reg_685 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_3_cast_fu_470_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_cast_reg_690 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_3_fu_492_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_3_reg_698 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln44_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_fu_508_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal lhs_reg_703 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln45_fu_516_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln45_reg_708 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal pollMatrix_addr_reg_713 : STD_LOGIC_VECTOR (2 downto 0);
    signal directions_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_reg_726 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal r_V_4_fu_542_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_4_reg_731 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal directions_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal directions_ce0 : STD_LOGIC;
    signal directions_we0 : STD_LOGIC;
    signal directions_ce1 : STD_LOGIC;
    signal directions_we1 : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_ap_start : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_ap_done : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_ap_idle : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_ap_ready : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_directions_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_generatePollDirections_fu_256_directions_ce0 : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_directions_we0 : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_directions_d0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_generatePollDirections_fu_256_directions_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_generatePollDirections_fu_256_directions_ce1 : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_directions_we1 : STD_LOGIC;
    signal grp_generatePollDirections_fu_256_directions_d1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mesh_V_1_09_reg_140 : STD_LOGIC_VECTOR (35 downto 0);
    signal mesh_V_0_08_reg_152 : STD_LOGIC_VECTOR (35 downto 0);
    signal currentPoint_int_V_1_07_reg_164 : STD_LOGIC_VECTOR (17 downto 0);
    signal currentPoint_int_V_0_06_reg_176 : STD_LOGIC_VECTOR (17 downto 0);
    signal i_reg_188 : STD_LOGIC_VECTOR (1 downto 0);
    signal randomVector_V_0_05_reg_199 : STD_LOGIC_VECTOR (17 downto 0);
    signal randomVector_V_1_04_reg_211 : STD_LOGIC_VECTOR (17 downto 0);
    signal i_1_reg_223 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_2_reg_234 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln45_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal j_reg_245 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_generatePollDirections_fu_256_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln46_fu_527_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_562_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_570_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln215_fu_313_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sh_prom_i_i_i54_fu_338_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal sh_prom_i_i_i_cast_cast_cast_fu_347_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_2_fu_331_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_341_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal r_V_1_fu_354_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal r_V_5_fu_360_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal trunc_ln708_1_fu_387_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal v_V_0_fu_396_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_2_fu_411_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal v_V_1_fu_420_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln43_fu_442_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_466_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_53_fu_484_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal empty_54_fu_488_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal empty_55_fu_500_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln46_fu_522_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ret_V_fu_547_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_562_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_570_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component MPCwithMADS_generatePollDirections IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (17 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (17 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (5 downto 0);
        directions_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        directions_ce0 : OUT STD_LOGIC;
        directions_we0 : OUT STD_LOGIC;
        directions_d0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        directions_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        directions_ce1 : OUT STD_LOGIC;
        directions_we1 : OUT STD_LOGIC;
        directions_d1 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component MPCwithMADS_mul_26s_12s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component MPCwithMADS_mul_mul_20s_6ns_20_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component MPCwithMADS_generatePollMatrix_directions IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (11 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    directions_U : component MPCwithMADS_generatePollMatrix_directions
    generic map (
        DataWidth => 12,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => directions_address0,
        ce0 => directions_ce0,
        we0 => directions_we0,
        d0 => grp_generatePollDirections_fu_256_directions_d0,
        q0 => directions_q0,
        address1 => grp_generatePollDirections_fu_256_directions_address1,
        ce1 => directions_ce1,
        we1 => directions_we1,
        d1 => grp_generatePollDirections_fu_256_directions_d1);

    grp_generatePollDirections_fu_256 : component MPCwithMADS_generatePollDirections
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_generatePollDirections_fu_256_ap_start,
        ap_done => grp_generatePollDirections_fu_256_ap_done,
        ap_idle => grp_generatePollDirections_fu_256_ap_idle,
        ap_ready => grp_generatePollDirections_fu_256_ap_ready,
        p_read => randomVector_V_0_05_reg_199,
        p_read1 => randomVector_V_1_04_reg_211,
        p_read2 => p_read,
        p_read3 => p_read1,
        p_read4 => p_read2,
        p_read5 => p_read3,
        directions_address0 => grp_generatePollDirections_fu_256_directions_address0,
        directions_ce0 => grp_generatePollDirections_fu_256_directions_ce0,
        directions_we0 => grp_generatePollDirections_fu_256_directions_we0,
        directions_d0 => grp_generatePollDirections_fu_256_directions_d0,
        directions_address1 => grp_generatePollDirections_fu_256_directions_address1,
        directions_ce1 => grp_generatePollDirections_fu_256_directions_ce1,
        directions_we1 => grp_generatePollDirections_fu_256_directions_we1,
        directions_d1 => grp_generatePollDirections_fu_256_directions_d1);

    mul_26s_12s_26_1_1_U92 : component MPCwithMADS_mul_26s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => r_V_3_reg_698,
        din1 => tmp_3_reg_726,
        dout => r_V_4_fu_542_p2);

    mul_mul_20s_6ns_20_4_1_U93 : component MPCwithMADS_mul_mul_20s_6ns_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 20,
        din1_WIDTH => 6,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => R1_V,
        din1 => grp_fu_562_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_562_p2);

    mul_mul_20s_6ns_20_4_1_U94 : component MPCwithMADS_mul_mul_20s_6ns_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 20,
        din1_WIDTH => 6,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => R2_V,
        din1 => grp_fu_570_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_570_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_generatePollDirections_fu_256_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_generatePollDirections_fu_256_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_fu_436_p2 = ap_const_lv1_1))) then 
                    grp_generatePollDirections_fu_256_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_generatePollDirections_fu_256_ap_ready = ap_const_logic_1)) then 
                    grp_generatePollDirections_fu_256_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_fu_436_p2 = ap_const_lv1_0))) then 
                i_1_reg_223 <= add_ln42_fu_430_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_1_reg_223 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    i_2_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_generatePollDirections_fu_256_ap_done = ap_const_logic_1))) then 
                i_2_reg_234 <= ap_const_lv2_0;
            elsif (((icmp_ln45_fu_533_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                i_2_reg_234 <= add_ln44_reg_685;
            end if; 
        end if;
    end process;

    i_reg_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_188 <= add_ln19_reg_606;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_188 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                j_reg_245 <= add_ln45_reg_708;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln44_fu_478_p2 = ap_const_lv1_0))) then 
                j_reg_245 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                R1_V <= grp_fu_562_p2;
                R2_V <= grp_fu_570_p2;
                sext_ln708_1_reg_662 <= sext_ln708_1_fu_426_p1;
                sext_ln708_reg_657 <= sext_ln708_fu_402_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln19_reg_606 <= add_ln19_fu_277_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                add_ln44_reg_685 <= add_ln44_fu_460_p2;
                    tmp_3_cast_reg_690(2) <= tmp_3_cast_fu_470_p3(2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln45_reg_708 <= add_ln45_fu_516_p2;
                pollMatrix_addr_reg_713 <= zext_ln46_fu_527_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                currentPoint_int_V_0_06_reg_176 <= currentPoint_int_V_1_1_reg_625;
                currentPoint_int_V_1_07_reg_164 <= currentPoint_int_V_1_reg_620;
                mesh_V_0_08_reg_152 <= mesh_V_1_2_fu_375_p3;
                mesh_V_1_09_reg_140 <= mesh_V_1_1_fu_368_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln19_fu_283_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                currentPoint_int_V_1_1_reg_625 <= currentPoint_int_V_1_1_fu_300_p3;
                currentPoint_int_V_1_reg_620 <= currentPoint_int_V_1_fu_293_p3;
                ret_reg_636 <= ret_fu_317_p2;
                rhs_reg_630 <= rhs_fu_307_p3;
                trunc_ln20_reg_614 <= trunc_ln20_fu_289_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln44_fu_478_p2 = ap_const_lv1_0))) then
                    lhs_reg_703(25 downto 8) <= lhs_fu_508_p3(25 downto 8);
                r_V_3_reg_698 <= r_V_3_fu_492_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                r_V_4_reg_731 <= r_V_4_fu_542_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_fu_436_p2 = ap_const_lv1_0))) then
                randomVector_V_0_05_reg_199 <= randomVector_V_1_fu_446_p3;
                randomVector_V_1_04_reg_211 <= randomVector_V_1_1_fu_453_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                tmp_3_reg_726 <= directions_q0;
            end if;
        end if;
    end process;
    tmp_3_cast_reg_690(1 downto 0) <= "00";
    lhs_reg_703(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln19_fu_283_p2, ap_CS_fsm_state7, icmp_ln42_fu_436_p2, ap_CS_fsm_state9, icmp_ln44_fu_478_p2, ap_CS_fsm_state10, grp_generatePollDirections_fu_256_ap_done, icmp_ln45_fu_533_p2, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln19_fu_283_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_fu_436_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_generatePollDirections_fu_256_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln44_fu_478_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                if (((icmp_ln45_fu_533_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln19_fu_277_p2 <= std_logic_vector(unsigned(i_reg_188) + unsigned(ap_const_lv2_1));
    add_ln42_fu_430_p2 <= std_logic_vector(unsigned(i_1_reg_223) + unsigned(ap_const_lv2_1));
    add_ln44_fu_460_p2 <= std_logic_vector(unsigned(i_2_reg_234) + unsigned(ap_const_lv2_1));
    add_ln45_fu_516_p2 <= std_logic_vector(unsigned(j_reg_245) + unsigned(ap_const_lv3_1));
    add_ln46_fu_522_p2 <= std_logic_vector(unsigned(tmp_3_cast_reg_690) + unsigned(j_reg_245));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state9, icmp_ln44_fu_478_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln44_fu_478_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9, icmp_ln44_fu_478_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln44_fu_478_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    currentPoint_int_V_1_1_fu_300_p3 <= 
        currentPoint_int_V_0_06_reg_176 when (trunc_ln20_fu_289_p1(0) = '1') else 
        optimum_V_0;
    currentPoint_int_V_1_fu_293_p3 <= 
        optimum_V_1 when (trunc_ln20_fu_289_p1(0) = '1') else 
        currentPoint_int_V_1_07_reg_164;

    directions_address0_assign_proc : process(ap_CS_fsm_state10, grp_generatePollDirections_fu_256_directions_address0, ap_CS_fsm_state8, zext_ln46_fu_527_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            directions_address0 <= zext_ln46_fu_527_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            directions_address0 <= grp_generatePollDirections_fu_256_directions_address0;
        else 
            directions_address0 <= "XXX";
        end if; 
    end process;


    directions_ce0_assign_proc : process(ap_CS_fsm_state10, grp_generatePollDirections_fu_256_directions_ce0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            directions_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            directions_ce0 <= grp_generatePollDirections_fu_256_directions_ce0;
        else 
            directions_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    directions_ce1_assign_proc : process(grp_generatePollDirections_fu_256_directions_ce1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            directions_ce1 <= grp_generatePollDirections_fu_256_directions_ce1;
        else 
            directions_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    directions_we0_assign_proc : process(grp_generatePollDirections_fu_256_directions_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            directions_we0 <= grp_generatePollDirections_fu_256_directions_we0;
        else 
            directions_we0 <= ap_const_logic_0;
        end if; 
    end process;


    directions_we1_assign_proc : process(grp_generatePollDirections_fu_256_directions_we1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            directions_we1 <= grp_generatePollDirections_fu_256_directions_we1;
        else 
            directions_we1 <= ap_const_logic_0;
        end if; 
    end process;

    empty_53_fu_484_p1 <= mesh_V_1_09_reg_140(26 - 1 downto 0);
    empty_54_fu_488_p1 <= mesh_V_0_08_reg_152(26 - 1 downto 0);
    empty_55_fu_500_p3 <= 
        currentPoint_int_V_1_07_reg_164 when (trunc_ln46_fu_466_p1(0) = '1') else 
        currentPoint_int_V_0_06_reg_176;
    grp_fu_562_p1 <= ap_const_lv20_1B(6 - 1 downto 0);
    grp_fu_570_p1 <= ap_const_lv20_1B(6 - 1 downto 0);
    grp_generatePollDirections_fu_256_ap_start <= grp_generatePollDirections_fu_256_ap_start_reg;
    icmp_ln19_fu_283_p2 <= "1" when (i_reg_188 = ap_const_lv2_2) else "0";
    icmp_ln42_fu_436_p2 <= "1" when (i_1_reg_223 = ap_const_lv2_2) else "0";
    icmp_ln44_fu_478_p2 <= "1" when (i_2_reg_234 = ap_const_lv2_2) else "0";
    icmp_ln45_fu_533_p2 <= "1" when (j_reg_245 = ap_const_lv3_4) else "0";
    lhs_fu_508_p3 <= (empty_55_fu_500_p3 & ap_const_lv8_0);
    mesh_V_1_1_fu_368_p3 <= 
        r_V_5_fu_360_p3 when (trunc_ln20_reg_614(0) = '1') else 
        mesh_V_1_09_reg_140;
    mesh_V_1_2_fu_375_p3 <= 
        mesh_V_0_08_reg_152 when (trunc_ln20_reg_614(0) = '1') else 
        r_V_5_fu_360_p3;
    pollMatrix_address0 <= pollMatrix_addr_reg_713;

    pollMatrix_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            pollMatrix_ce0 <= ap_const_logic_1;
        else 
            pollMatrix_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pollMatrix_d0 <= ret_V_fu_547_p2(25 downto 8);

    pollMatrix_we0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            pollMatrix_we0 <= ap_const_logic_1;
        else 
            pollMatrix_we0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_354_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv36_1000000),to_integer(unsigned('0' & sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1(31-1 downto 0)))));
    r_V_3_fu_492_p3 <= 
        empty_53_fu_484_p1 when (trunc_ln46_fu_466_p1(0) = '1') else 
        empty_54_fu_488_p1;
    r_V_5_fu_360_p3 <= 
        r_V_fu_341_p2 when (tmp_2_fu_331_p3(0) = '1') else 
        r_V_1_fu_354_p2;
    r_V_fu_341_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv36_1000000),to_integer(unsigned('0' & sh_prom_i_i_i54_fu_338_p1(31-1 downto 0)))));
    randomVector_V_1_1_fu_453_p3 <= 
        sext_ln708_1_reg_662 when (trunc_ln43_fu_442_p1(0) = '1') else 
        randomVector_V_1_04_reg_211;
    randomVector_V_1_fu_446_p3 <= 
        randomVector_V_0_05_reg_199 when (trunc_ln43_fu_442_p1(0) = '1') else 
        sext_ln708_reg_657;
    ret_V_fu_547_p2 <= std_logic_vector(unsigned(lhs_reg_703) + unsigned(r_V_4_reg_731));
    ret_fu_317_p2 <= std_logic_vector(unsigned(ap_const_lv7_0) - unsigned(sext_ln215_fu_313_p1));
    rhs_fu_307_p3 <= 
        p_read3 when (trunc_ln20_fu_289_p1(0) = '1') else 
        p_read2;
        sext_ln215_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_fu_307_p3),7));

        sext_ln708_1_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(v_V_1_fu_420_p2),18));

        sext_ln708_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(v_V_0_fu_396_p2),18));

    sh_prom_i_i_i54_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_reg_636),36));
    sh_prom_i_i_i_cast_cast_cast_cast_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_prom_i_i_i_cast_cast_cast_fu_347_p1),36));
        sh_prom_i_i_i_cast_cast_cast_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_reg_630),32));

    tmp_2_fu_331_p3 <= rhs_reg_630(5 downto 5);
    tmp_3_cast_fu_470_p3 <= (trunc_ln46_fu_466_p1 & ap_const_lv2_0);
    trunc_ln20_fu_289_p1 <= i_reg_188(1 - 1 downto 0);
    trunc_ln43_fu_442_p1 <= i_1_reg_223(1 - 1 downto 0);
    trunc_ln46_fu_466_p1 <= i_2_reg_234(1 - 1 downto 0);
    trunc_ln708_1_fu_387_p4 <= grp_fu_562_p2(19 downto 4);
    trunc_ln708_2_fu_411_p4 <= grp_fu_570_p2(19 downto 4);
    v_V_0_fu_396_p2 <= (trunc_ln708_1_fu_387_p4 xor ap_const_lv16_8000);
    v_V_1_fu_420_p2 <= (trunc_ln708_2_fu_411_p4 xor ap_const_lv16_8000);
    zext_ln46_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_fu_522_p2),64));
end behav;
